<?php require __DIR__ . '/auth.php'; migrate_legacy_data(); require_login(); ?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Signage – Zentrale Display-Steuerung</title><style>body{font-family:sans-serif;max-width:720px;margin:30px auto;padding:25px}label{display:block;margin-top:12px;font-weight:bold}input,select,button{padding:9px;margin-top:4px;box-sizing:border-box}input,select{width:100%}button{cursor:pointer}table{width:100%;border-collapse:collapse;margin-top:15px}td,th{padding:8px;border:1px solid #ddd;text-align:left}.actions{display:flex;gap:6px}.message{color:green}</style></head><body>
<h1>Zentrale Display-Steuerung</h1><p><a href="screens.php">Displays &amp; Tokens</a> · <a href="change_password.php">Passwort ändern</a> · <a href="logout.php">Abmelden</a></p><?php if (isset($_GET['message'])): ?><p class="message"><?= h((string) $_GET['message']) ?></p><?php endif; ?>
<form action="upload.php" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><label>Bildschirm<select name="display_typ" required><?php foreach (SCREEN_IDS as $screen): ?><option value="<?= h($screen) ?>"><?= h(ucfirst($screen)) ?>-Display</option><?php endforeach; ?></select></label><label>Von<input type="datetime-local" name="start_zeit" id="start_zeit" required></label><label>Bis<input type="datetime-local" name="ende_zeit" id="ende_zeit" required></label><label>Bild / Grafik (JPG)<input type="file" name="menue_bild" accept="image/jpeg,.jpg,.jpeg" required></label><button>Event speichern</button></form>
<h2>Geplante Displays &amp; Programme</h2><table><thead><tr><th>Datei</th><th>Display</th><th>Von</th><th>Bis</th><th>Aktion</th></tr></thead><tbody id="events"><tr><td colspan="5">Lade Events…</td></tr></tbody></table>
<script>
const csrf=<?= json_encode(csrf_token()) ?>;const pad=n=>String(n).padStart(2,'0');const local=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;const now=new Date(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);document.querySelector('#start_zeit').value=local(new Date(now.getFullYear(),now.getMonth(),now.getDate(),12));document.querySelector('#ende_zeit').value=local(new Date(tomorrow.getFullYear(),tomorrow.getMonth(),tomorrow.getDate(),8));
function cell(text){const td=document.createElement('td');td.textContent=text;return td}async function load(){try{const response=await fetch('events.php',{cache:'no-store'});if(!response.ok)throw Error();const list=await response.json(),body=document.querySelector('#events');body.replaceChildren();list.sort((a,b)=>a.start.localeCompare(b.start));if(!list.length){body.innerHTML='<tr><td colspan="5">Aktuell keine Events geplant.</td></tr>';return}for(const e of list){const tr=document.createElement('tr');tr.append(cell(e.original_name||'Datei'),cell(e.display),cell(e.start),cell(e.ende));const actions=document.createElement('td'),form=document.createElement('form');form.method='post';form.action='upload.php';form.className='actions';for(const [name,value] of Object.entries({csrf,action:'delete',loesch_bild:e.bild})){const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.append(input)}const button=document.createElement('button');button.textContent='Löschen';button.onclick=()=>confirm('Dieses Event löschen?');form.append(button);actions.append(form);tr.append(actions);body.append(tr)}}catch{document.querySelector('#events').innerHTML='<tr><td colspan="5">Events konnten nicht geladen werden.</td></tr>'}}load();
</script></body></html>
