<?php
require __DIR__ . '/auth.php'; require_login();
$error = ''; $edit = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') { require_csrf(); $action = (string) ($_POST['action'] ?? ''); $id = (string) ($_POST['id'] ?? '');
    if (!display_id_valid($id)) $error = 'ID must contain only letters, numbers, hyphens, and underscores.';
    else with_data_lock(function () use ($action, $id, &$error): void { $all = displays(); $index = array_search($id, array_column($all, 'id'), true);
        if ($action === 'delete') { if ($index === false) { $error = 'Display not found.'; return; } foreach (events() as $event) if (($event['display'] ?? '') === $id) { $error = 'Delete this display’s scheduled events first.'; return; } array_splice($all, $index, 1); save_displays($all); return; }
        $name = trim((string) ($_POST['name'] ?? '')); $orientation = filter_var($_POST['orientation'] ?? null, FILTER_VALIDATE_INT);
        if ($name === '' || $orientation === false || !in_array($orientation, [0, 90, 180, 270], true)) { $error = 'Name and orientation are required.'; return; }
        $original = (string) ($_POST['original_id'] ?? ''); if ($original !== '' && $original !== $id) { $error = 'Display IDs cannot be changed.'; return; }
        if ($index !== false) $all[$index] = ['id' => $id, 'name' => $name, 'orientation' => $orientation]; else $all[] = ['id' => $id, 'name' => $name, 'orientation' => $orientation]; save_displays($all);
    });
    if ($error === '') { header('Location: screens.php'); exit; }
}
if (isset($_GET['edit'])) $edit = display_by_id((string) $_GET['edit']);
$form = $edit ?? ['id' => '', 'name' => '', 'orientation' => 0];
?><!doctype html><html lang="en"><meta charset="utf-8"><title>Displays</title><style>body{font-family:sans-serif;max-width:760px;margin:30px auto;padding:20px}label{display:block;margin:10px 0}input,select,button{padding:8px}table{border-collapse:collapse;width:100%;margin-top:20px}td,th{border:1px solid #ddd;padding:8px;text-align:left}.actions{display:inline}</style><body><h1>Displays</h1><p><a href="formular.php">Content administration</a></p><?php if ($error): ?><p><?= h($error) ?></p><?php endif; ?><h2><?= $edit ? 'Edit display' : 'Create display' ?></h2><form method="post"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="original_id" value="<?= h($edit['id'] ?? '') ?>"><label>ID <input name="id" pattern="[A-Za-z0-9_-]+" value="<?= h($form['id']) ?>" <?= $edit ? 'readonly' : '' ?> required></label><label>Name <input name="name" value="<?= h($form['name']) ?>" required></label><label>Orientation <select name="orientation"><?php foreach ([0,90,180,270] as $o): ?><option value="<?= $o ?>" <?= $form['orientation'] === $o ? 'selected' : '' ?>><?= $o ?>°</option><?php endforeach; ?></select></label><button>Save display</button><?php if ($edit): ?> <a href="screens.php">Cancel</a><?php endif; ?></form><h2>Configured displays</h2><table><tr><th>ID</th><th>Name</th><th>Orientation</th><th>Playback URL</th><th>Actions</th></tr><?php foreach (displays() as $display): ?><tr><td><?= h($display['id']) ?></td><td><?= h($display['name']) ?></td><td><?= (int) $display['orientation'] ?>°</td><td><code>display.php?screen=<?= rawurlencode($display['id']) ?></code></td><td><a href="screens.php?edit=<?= rawurlencode($display['id']) ?>">Edit</a> <form method="post" class="actions" onsubmit="return confirm('Delete this display?');"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= h($display['id']) ?>"><button>Delete</button></form></td></tr><?php endforeach; ?></table></body></html>
